export const KingdomLogo = {
  light: require('./logo.png'),
  dark: require('./logo.png'),
};

export const images = {
  blogImage: require('./blog_image.png'),
  isbankasi: require('./isbankasi.png'),
  fibabank: require('./fibabank.png'),
  akbank: require('./akbank.png'),
  success: require('./success.png'),
  successMessage: require('./success-message.png'),
  confirmed: require('./confirmed.png'),
  warning: require('./warning.png'),
  calendarWarning: require('./calendar_warning.png'),
  bgArrows: require('./bg-arrows.png'),
  figoLoader: require('./figo-loader.png'),
  computer: require('./computer.png'),
  papara: require('./papara.png'),
  eczacibasi: require('./eczacibasi.png'),
  figo: require('./mini-figo-logo.png'),
  googleCalendar: require('./google-calendar.png'),
  googleCalendarV2: require('./google-calendar-v2.png'),
  appleCalendar: require('./apple-calendar.png'),
  ssl: require('./ssl.png'),
  dips: require('./dips.jpg'),
  blog: require('./blog.png'),
  background: require('./background.png'),
  backgroundSoft: require('./background-soft.png'),
  exercise: require('./exercise-min.jpg'),
  lime: require('./lime.png'),
  avatar: require('./avatar.png'),
};
